baseURL: 'https://thien.dev/'
languageCode: vi-vn
copyright: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.
title: Thien Nguyen
theme: blog
enableGitInfo: false
enableEmoji: true
enableRobotsTXT: true
googleAnalytics: UA-135910674-1
uglyURLs: true
paginate: 40
outputs:
  home:
  - HTML
  - RSS
params:
  description: Mostly working with WordPress and front-end stuff. Particularly interested in open source, startup, and design.
  favicon: img/icon/favicon.png
  images:
    - img/index.png
  facebookAppId: 363747664413304
blackfriday:
  hrefTargetBlank: true
  noreferrerLinks: true
menu:
  main:
  - identifier: contact
    title: Contact
    url: /pages/contact.html
